//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;

using LinqToDB;
using LinqToDB.Mapping;

namespace rels.Model
{
	/// <summary>
	/// Database       : rels
	/// Data Source    : rels
	/// Server Version : 3.24.0
	/// </summary>
	public partial class RelsDB : LinqToDB.Data.DataConnection
	{
		public RelsDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public RelsDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}
}

#pragma warning restore 1591
